// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DS4-HFRGgNwhSYjcFx6Wq7O5fihGklg',
    appId: '1:1018059420299:android:c8093f9a583fc45ab49a8e',
    messagingSenderId: '1018059420299',
    projectId: 'just-for-test-2c462',
    storageBucket: 'just-for-test-2c462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhTXOlpvD0vsti4otzd4VcrSPPUgS8oE',
    appId: '1:1018059420299:ios:571580559f18dd64b49a8e',
    messagingSenderId: '1018059420299',
    projectId: 'just-for-test-2c462',
    storageBucket: 'just-for-test-2c462.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBD8rgWhsn7nIg-Jd1w4YXadrlf9AHhb8',
    appId: '1:1018059420299:web:e3c55f8a9023bafcb49a8e',
    messagingSenderId: '1018059420299',
    projectId: 'just-for-test-2c462',
    authDomain: 'just-for-test-2c462.firebaseapp.com',
    storageBucket: 'just-for-test-2c462.firebasestorage.app',
    measurementId: 'G-Z6ZZG4R5JQ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBD8rgWhsn7nIg-Jd1w4YXadrlf9AHhb8',
    appId: '1:1018059420299:web:10ff43d2ec5225c3b49a8e',
    messagingSenderId: '1018059420299',
    projectId: 'just-for-test-2c462',
    authDomain: 'just-for-test-2c462.firebaseapp.com',
    storageBucket: 'just-for-test-2c462.firebasestorage.app',
    measurementId: 'G-D0P01FHWCV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRhTXOlpvD0vsti4otzd4VcrSPPUgS8oE',
    appId: '1:1018059420299:ios:571580559f18dd64b49a8e',
    messagingSenderId: '1018059420299',
    projectId: 'just-for-test-2c462',
    storageBucket: 'just-for-test-2c462.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

}